export interface CountryDefaults {
  overheadPct: number; // as decimal (e.g., 0.25 = 25%)
  hoursPerDay: number;
  vacationDays: number;
  publicHolidays: number;
  otherLeaveDays: number;
  trainingDays: number;
}

export const countryDefaults: Record<string, CountryDefaults> = {
  'GLOBAL': {
    overheadPct: 0.25,
    hoursPerDay: 8,
    vacationDays: 21,
    publicHolidays: 15,
    otherLeaveDays: 10,
    trainingDays: 4,
  },
  'US': {
    overheadPct: 0.25,
    hoursPerDay: 8,
    vacationDays: 15,
    publicHolidays: 10,
    otherLeaveDays: 5,
    trainingDays: 3,
  },
  'CA': {
    overheadPct: 0.28,
    hoursPerDay: 8,
    vacationDays: 15,
    publicHolidays: 9,
    otherLeaveDays: 5,
    trainingDays: 3,
  },
  'MX': {
    overheadPct: 0.22,
    hoursPerDay: 8,
    vacationDays: 12,
    publicHolidays: 8,
    otherLeaveDays: 4,
    trainingDays: 3,
  },
  'GB': {
    overheadPct: 0.26,
    hoursPerDay: 7.5,
    vacationDays: 28,
    publicHolidays: 8,
    otherLeaveDays: 5,
    trainingDays: 4,
  },
  'DE': {
    overheadPct: 0.30,
    hoursPerDay: 8,
    vacationDays: 30,
    publicHolidays: 10,
    otherLeaveDays: 5,
    trainingDays: 4,
  },
  'FR': {
    overheadPct: 0.42,
    hoursPerDay: 7,
    vacationDays: 30,
    publicHolidays: 11,
    otherLeaveDays: 5,
    trainingDays: 4,
  },
  'NL': {
    overheadPct: 0.28,
    hoursPerDay: 8,
    vacationDays: 25,
    publicHolidays: 8,
    otherLeaveDays: 5,
    trainingDays: 4,
  },
  'ES': {
    overheadPct: 0.27,
    hoursPerDay: 8,
    vacationDays: 30,
    publicHolidays: 14,
    otherLeaveDays: 5,
    trainingDays: 4,
  },
  'SE': {
    overheadPct: 0.35,
    hoursPerDay: 8,
    vacationDays: 25,
    publicHolidays: 13,
    otherLeaveDays: 5,
    trainingDays: 5,
  },
  'CH': {
    overheadPct: 0.24,
    hoursPerDay: 8.4,
    vacationDays: 25,
    publicHolidays: 9,
    otherLeaveDays: 5,
    trainingDays: 4,
  },
  'SG': {
    overheadPct: 0.20,
    hoursPerDay: 8,
    vacationDays: 14,
    publicHolidays: 11,
    otherLeaveDays: 4,
    trainingDays: 3,
  },
  'JP': {
    overheadPct: 0.26,
    hoursPerDay: 8,
    vacationDays: 10,
    publicHolidays: 16,
    otherLeaveDays: 4,
    trainingDays: 3,
  },
  'AU': {
    overheadPct: 0.25,
    hoursPerDay: 7.6,
    vacationDays: 20,
    publicHolidays: 11,
    otherLeaveDays: 5,
    trainingDays: 4,
  },
  'IN': {
    overheadPct: 0.18,
    hoursPerDay: 8,
    vacationDays: 12,
    publicHolidays: 12,
    otherLeaveDays: 4,
    trainingDays: 3,
  },
  'PH': {
    overheadPct: 0.16,
    hoursPerDay: 8,
    vacationDays: 10,
    publicHolidays: 12,
    otherLeaveDays: 3,
    trainingDays: 2,
  },
  'BR': {
    overheadPct: 0.35,
    hoursPerDay: 8,
    vacationDays: 30,
    publicHolidays: 12,
    otherLeaveDays: 5,
    trainingDays: 4,
  },
  'AR': {
    overheadPct: 0.25,
    hoursPerDay: 8,
    vacationDays: 14,
    publicHolidays: 14,
    otherLeaveDays: 4,
    trainingDays: 3,
  },
  'CL': {
    overheadPct: 0.23,
    hoursPerDay: 8,
    vacationDays: 15,
    publicHolidays: 15,
    otherLeaveDays: 4,
    trainingDays: 3,
  },
  'ZA': {
    overheadPct: 0.22,
    hoursPerDay: 8,
    vacationDays: 15,
    publicHolidays: 12,
    otherLeaveDays: 4,
    trainingDays: 3,
  },
  'KE': {
    overheadPct: 0.18,
    hoursPerDay: 8,
    vacationDays: 21,
    publicHolidays: 11,
    otherLeaveDays: 4,
    trainingDays: 3,
  },
  'AE': {
    overheadPct: 0.15,
    hoursPerDay: 8,
    vacationDays: 22,
    publicHolidays: 13,
    otherLeaveDays: 5,
    trainingDays: 3,
  },
  'OTHER': {
    overheadPct: 0.25,
    hoursPerDay: 8,
    vacationDays: 21,
    publicHolidays: 15,
    otherLeaveDays: 5,
    trainingDays: 4,
  },
};

export const countryOptions = [
  { value: 'AR', label: 'Argentina' },
  { value: 'AR', label: 'Argentina' },
  { value: 'AU', label: 'Australia' },
  { value: 'BR', label: 'Brazil' },
  { value: 'CA', label: 'Canada' },
  { value: 'CL', label: 'Chile' },
  { value: 'FR', label: 'France' },
  { value: 'DE', label: 'Germany' },
  { value: 'IN', label: 'India' },
  { value: 'JP', label: 'Japan' },
  { value: 'KE', label: 'Kenya' },
  { value: 'MX', label: 'Mexico' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'PH', label: 'Philippines' },
  { value: 'SG', label: 'Singapore' },
  { value: 'ZA', label: 'South Africa' },
  { value: 'ES', label: 'Spain' },
  { value: 'SE', label: 'Sweden' },
  { value: 'CH', label: 'Switzerland' },
  { value: 'AE', label: 'UAE' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'US', label: 'United States' },
  { value: 'OTHER', label: 'Other' },
];
